// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UddsPublisher.h
 * This header file contains the declaration of the publisher functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _FAST_DDS_GENERATED_UDDS_PUBLISHER_H_
#define _FAST_DDS_GENERATED_UDDS_PUBLISHER_H_

#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/publisher/DataWriterListener.hpp>
#include <fastdds/dds/publisher/Publisher.hpp>
#include <fastdds/dds/topic/TypeSupport.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/dds/subscriber/DataReaderListener.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>
class Device
{
public:

    Device();

    virtual ~Device();

    bool init();

    friend void rgb_thread(Device& device);
    friend void depth_thread(Device& device);
    friend void devinfo_thread(Device& device);
private:

    eprosima::fastdds::dds::DomainParticipant* participant_;
    eprosima::fastdds::dds::Publisher* publisher_;
    eprosima::fastdds::dds::Subscriber* subscriber_;
    eprosima::fastdds::dds::Topic* devinfo_topic_;
    eprosima::fastdds::dds::Topic* cmd_topic_;
    eprosima::fastdds::dds::Topic* rgb_topic_;
    eprosima::fastdds::dds::Topic* depth_topic_;
    eprosima::fastdds::dds::DataWriter* rgb_writer_;
    eprosima::fastdds::dds::DataWriter* depth_writer_;
    eprosima::fastdds::dds::DataReader* cmd_reader_;
    eprosima::fastdds::dds::DataWriter* devinfo_writer_;
    eprosima::fastdds::dds::TypeSupport blob_type_;
    eprosima::fastdds::dds::TypeSupport headerblob1_type_;
    bool rgb_stream_ = false;
    bool depth_stream_ = false;

    class WriterListener : public eprosima::fastdds::dds::DataWriterListener
    {
    public:

        WriterListener() = default;

        ~WriterListener() override = default;

        void on_publication_matched(
                eprosima::fastdds::dds::DataWriter* writer,
                const eprosima::fastdds::dds::PublicationMatchedStatus& info) override;

        int matched = 0;
        Device* owner;
    }
    writer_listener_;

    class ReaderListener : public eprosima::fastdds::dds::DataReaderListener
    {
    public:

        ReaderListener() = default;

        ~ReaderListener() override = default;

        void on_data_available(
            eprosima::fastdds::dds::DataReader* reader) override;

        void on_subscription_matched(
            eprosima::fastdds::dds::DataReader* reader,
            const eprosima::fastdds::dds::SubscriptionMatchedStatus& info) override;

        int matched = 0;
        uint32_t samples = 0;
        Device* owner;
    }
    reader_listener_;
};

#endif // _FAST_DDS_GENERATED_UDDS_PUBLISHER_H_