// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Udds.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Udds.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Blob::Blob()
{
    // m_data com.eprosima.idl.parser.typecode.SequenceTypeCode@73846619


}

Blob::~Blob()
{
}

Blob::Blob(
        const Blob& x)
{
    m_data = x.m_data;
}

Blob::Blob(
        Blob&& x) noexcept 
{
    m_data = std::move(x.m_data);
}

Blob& Blob::operator =(
        const Blob& x)
{

    m_data = x.m_data;

    return *this;
}

Blob& Blob::operator =(
        Blob&& x) noexcept
{

    m_data = std::move(x.m_data);

    return *this;
}

bool Blob::operator ==(
        const Blob& x) const
{

    return (m_data == x.m_data);
}

bool Blob::operator !=(
        const Blob& x) const
{
    return !(*this == x);
}

size_t Blob::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

size_t Blob::getCdrSerializedSize(
        const Blob& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.data().size() > 0)
    {
        current_alignment += (data.data().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }



    return current_alignment - initial_alignment;
}

void Blob::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_data;
}

void Blob::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_data;}

/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void Blob::data(
        const std::vector<uint8_t>& _data)
{
    m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void Blob::data(
        std::vector<uint8_t>&& _data)
{
    m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::vector<uint8_t>& Blob::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::vector<uint8_t>& Blob::data()
{
    return m_data;
}

size_t Blob::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool Blob::isKeyDefined()
{
    return false;
}

void Blob::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}

HeaderBlob1::HeaderBlob1()
{
    // m_header com.eprosima.idl.parser.typecode.SequenceTypeCode@192b07fd

    // m_data com.eprosima.idl.parser.typecode.SequenceTypeCode@64bfbc86


}

HeaderBlob1::~HeaderBlob1()
{


}

HeaderBlob1::HeaderBlob1(
        const HeaderBlob1& x)
{
    m_header = x.m_header;
    m_data = x.m_data;
}

HeaderBlob1::HeaderBlob1(
        HeaderBlob1&& x) noexcept 
{
    m_header = std::move(x.m_header);
    m_data = std::move(x.m_data);
}

HeaderBlob1& HeaderBlob1::operator =(
        const HeaderBlob1& x)
{

    m_header = x.m_header;
    m_data = x.m_data;

    return *this;
}

HeaderBlob1& HeaderBlob1::operator =(
        HeaderBlob1&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_data = std::move(x.m_data);

    return *this;
}

bool HeaderBlob1::operator ==(
        const HeaderBlob1& x) const
{

    return (m_header == x.m_header && m_data == x.m_data);
}

bool HeaderBlob1::operator !=(
        const HeaderBlob1& x) const
{
    return !(*this == x);
}

size_t HeaderBlob1::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);




    return current_alignment - initial_alignment;
}

size_t HeaderBlob1::getCdrSerializedSize(
        const HeaderBlob1& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.header().size() > 0)
    {
        current_alignment += (data.header().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.data().size() > 0)
    {
        current_alignment += (data.data().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }




    return current_alignment - initial_alignment;
}

void HeaderBlob1::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_data;
}

void HeaderBlob1::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_data;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void HeaderBlob1::header(
        const std::vector<uint8_t>& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void HeaderBlob1::header(
        std::vector<uint8_t>&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std::vector<uint8_t>& HeaderBlob1::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std::vector<uint8_t>& HeaderBlob1::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void HeaderBlob1::data(
        const std::vector<uint8_t>& _data)
{
    m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void HeaderBlob1::data(
        std::vector<uint8_t>&& _data)
{
    m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::vector<uint8_t>& HeaderBlob1::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::vector<uint8_t>& HeaderBlob1::data()
{
    return m_data;
}

size_t HeaderBlob1::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool HeaderBlob1::isKeyDefined()
{
    return false;
}

void HeaderBlob1::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}

HeaderBlob2::HeaderBlob2()
{
    // m_header com.eprosima.idl.parser.typecode.SequenceTypeCode@6e1ec318

    // m_data1 com.eprosima.idl.parser.typecode.SequenceTypeCode@7e0b0338

    // m_data2 com.eprosima.idl.parser.typecode.SequenceTypeCode@617faa95


}

HeaderBlob2::~HeaderBlob2()
{



}

HeaderBlob2::HeaderBlob2(
        const HeaderBlob2& x)
{
    m_header = x.m_header;
    m_data1 = x.m_data1;
    m_data2 = x.m_data2;
}

HeaderBlob2::HeaderBlob2(
        HeaderBlob2&& x) noexcept 
{
    m_header = std::move(x.m_header);
    m_data1 = std::move(x.m_data1);
    m_data2 = std::move(x.m_data2);
}

HeaderBlob2& HeaderBlob2::operator =(
        const HeaderBlob2& x)
{

    m_header = x.m_header;
    m_data1 = x.m_data1;
    m_data2 = x.m_data2;

    return *this;
}

HeaderBlob2& HeaderBlob2::operator =(
        HeaderBlob2&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_data1 = std::move(x.m_data1);
    m_data2 = std::move(x.m_data2);

    return *this;
}

bool HeaderBlob2::operator ==(
        const HeaderBlob2& x) const
{

    return (m_header == x.m_header && m_data1 == x.m_data1 && m_data2 == x.m_data2);
}

bool HeaderBlob2::operator !=(
        const HeaderBlob2& x) const
{
    return !(*this == x);
}

size_t HeaderBlob2::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);




    return current_alignment - initial_alignment;
}

size_t HeaderBlob2::getCdrSerializedSize(
        const HeaderBlob2& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.header().size() > 0)
    {
        current_alignment += (data.header().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.data1().size() > 0)
    {
        current_alignment += (data.data1().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.data2().size() > 0)
    {
        current_alignment += (data.data2().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }




    return current_alignment - initial_alignment;
}

void HeaderBlob2::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_data1;
    scdr << m_data2;
}

void HeaderBlob2::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_data1;
    dcdr >> m_data2;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void HeaderBlob2::header(
        const std::vector<uint8_t>& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void HeaderBlob2::header(
        std::vector<uint8_t>&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std::vector<uint8_t>& HeaderBlob2::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std::vector<uint8_t>& HeaderBlob2::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member data1
 * @param _data1 New value to be copied in member data1
 */
void HeaderBlob2::data1(
        const std::vector<uint8_t>& _data1)
{
    m_data1 = _data1;
}

/*!
 * @brief This function moves the value in member data1
 * @param _data1 New value to be moved in member data1
 */
void HeaderBlob2::data1(
        std::vector<uint8_t>&& _data1)
{
    m_data1 = std::move(_data1);
}

/*!
 * @brief This function returns a constant reference to member data1
 * @return Constant reference to member data1
 */
const std::vector<uint8_t>& HeaderBlob2::data1() const
{
    return m_data1;
}

/*!
 * @brief This function returns a reference to member data1
 * @return Reference to member data1
 */
std::vector<uint8_t>& HeaderBlob2::data1()
{
    return m_data1;
}
/*!
 * @brief This function copies the value in member data2
 * @param _data2 New value to be copied in member data2
 */
void HeaderBlob2::data2(
        const std::vector<uint8_t>& _data2)
{
    m_data2 = _data2;
}

/*!
 * @brief This function moves the value in member data2
 * @param _data2 New value to be moved in member data2
 */
void HeaderBlob2::data2(
        std::vector<uint8_t>&& _data2)
{
    m_data2 = std::move(_data2);
}

/*!
 * @brief This function returns a constant reference to member data2
 * @return Constant reference to member data2
 */
const std::vector<uint8_t>& HeaderBlob2::data2() const
{
    return m_data2;
}

/*!
 * @brief This function returns a reference to member data2
 * @return Reference to member data2
 */
std::vector<uint8_t>& HeaderBlob2::data2()
{
    return m_data2;
}

size_t HeaderBlob2::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;






    return current_align;
}

bool HeaderBlob2::isKeyDefined()
{
    return false;
}

void HeaderBlob2::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}
