// License: Apache 2.0. See LICENSE file in root directory.
// Copyright(c) 2022 Intel Corporation. All Rights Reserved.

module realsense {

// The maximum payload size in the PoC is the one for the topic realsense/depth.
const uint32 DEPTH_IMAGE_WIDTH = 1280;
const uint32 DEPTH_IMAGE_HEIGHT = 960;
const uint32 DEPTH_BYTES_PER_PIXEL = 2;
const uint32 MAX_IMAGE_PAYLOAD_SIZE = DEPTH_IMAGE_WIDTH * DEPTH_IMAGE_HEIGHT * DEPTH_BYTES_PER_PIXEL;

@final
@verbatim (language="comment", text="Generic type for embedded to host topics")
struct STREAM_payload {
    uint64 stream_id;
    uint64 frame_number;
    sequence<octet, MAX_IMAGE_PAYLOAD_SIZE> payload;
};

@final
@verbatim (language="comment", text="Generic type for command topics")
struct OP_payload {
    uint64 op;
    uint64 id;
    uint64 data[5];
};

};  // module realsense
